### ISSUE TITLE
[GET/LIST] Endpoint for retrieving user club transactions

### ISSUE THREAD

**Issue by SelimAydi** [anti-social-engineers/AceCardAPI#20]
**Why?**
Users should be able to view and track all transactions made inside a club using their card.

**Where?**
This information will be visible in the dashboard of a user's account.
/Dashboard/Transacties

**Authorized users**
- User requesting data for itself
- Admin

**Parameters to be passed to endpoint**
```
{
    user_id: int
}
```

**Expected:**
```
{ 
    payment_id: int,
    amount: int,
    club_name: string,
    paid_at: string
}
```

**Comment by KyrumX** [comment]
> Parameters to be passed to endpoint
> ```
> {
>     user_id: int
> }
> ```

Will be removed. No input will be required, it will be done by passing the JWT.

**Comment by KyrumX** [comment]
Added with #26
