### ISSUE TITLE
[GET/LIST] Endpoint for retrieving user deposits

### ISSUE THREAD

**Issue by SelimAydi** [anti-social-engineers/AceCardAPI#21]
**Why?**
Users should be able to view and track all the deposits they made to their account, including its status (status will be handled through webhooks from stripe).

**Where**
This information can be viewed inside a user's dashboard, as well as in an admin's dashboard

**Authorized users**
- User requesting data for itself
- Admin

**Headers sent to endpoint**
Authorization: { JWT token }

**Parameters sent to endpoint**
```
{
    begin_date: string,
    end_date: string
}
```

**Expects**
```
{
    deposit_id: int,
    amount: int,
    deposited_at: string
}
```

**Comment by KyrumX** [comment]
> Parameters to be passed to endpoint
> ```
> {
>     user_id: int
> }
> ```

Will be removed. No input will be required, it will be done by passing the JWT.

**Comment by KyrumX** [comment]
Added with #26
